### ISSUE TITLE
Controlador y rutas Reservation

### ISSUE THREAD

**Issue by VCinthia** [VCinthia/BACKEND-C3-GRUPOMDQ-TP1#3]
**Reservations**
--

**Controllers para Reservations**

Archivo: `reservationController.js`
Descripción: Crear el controlador para gestionar la lógica de reservas (listar, crear, modificar, eliminar reservas).

- [x] Crear reserva
- [x] Obtener reservas
- [x] Obtener reserva
- [x] Editar reserva (cambia estado)
- [x] Obtener mesas disponibles

**Routes para Reservations**

Archivo: `reservations.js`
Descripción: Definir las rutas asociadas a la entidad Reservation, usando las funciones del controlador.

- [x] Crear reserva
- [x] Obtener reservas
- [x] Obtener reserva
- [x] Editar reserva (cambia estado)
- [x] Obtener mesas disponibles

**Comment by CynthiDev** [comment]
Se completaron todas las tares y se  agrego una capa mas que son lso servicios para manejar la logica de reservaciones
