### ISSUE TITLE
Vistas

### ISSUE THREAD

**Issue by VCinthia** [VCinthia/BACKEND-C3-GRUPOMDQ-TP1#5]
**Vistas del proyecto**
--

Descripción: Crear las vistas del sistema usando Pug, incluyendo las siguientes:

- Login: Pantalla inicial para que los usuarios inicien sesión.

- [x] Iniciar Sesion: Boton para realizar login.
  - [x] Formulario para ingresar credenciales y hacer login.
 

- Pantalla principal:
- [x] Gestion de Reservas: Boton para listar y gestionar reservas.
   - [x] Gestionar Reservas desde Cliente: Interfaz para que el cliente cambie el estado de sus reservas.
   - [x] Gestionar Reservas desde Personal: Interfaz para que el personal cambie el estado de las reservas o las elimine.
 - [x] Agregar Reserva: Boton que redirige a formulario.
   - [x] Formulario Reserva: Interfaz para que los clientes o el personal creen una reserva seleccionando fecha, hora, y mesa.
- [x] Logout: Boton para cerrar sesión y redirigir al login.

**Comment by garnicamatias** [comment]
En el formulario de reserva hardcodeé un listado de radio buttons con la información de fecha, hora y mesa, no se si esa será la mejor opción a la hora de traer los datos JSON. Lo dejo como completo pero a iterar si es necesario.

En gestionar reservas, tanto para personal como para clientes la tabla es idéntica (con un botón para confirmar y otro para eliminar reserva), cuando avancemos podría agregar un input para cuando el user es Personal.

**Comment by garnicamatias** [comment]
No quise meter mano con las funcionalidades de los botones para no ensuciar el código en app.js, espero a que se complete lo demás y ahí continúo (porque no se si por ejemplo Iniciar sesión lo maneja userController.js y no quería pisar ese trabajo de otro de ustedes)
